version: '3.1'

services:
  db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
        - 5432:5432
    volumes:
        - ./postgres/init:/docker-entrypoint-initdb.d
